name: CI/CD Pipeline for To-Do List Website

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: |
        docker build -t todolist-web:latest .
        docker tag todolist-web:latest sathwik1610/todolist-web:latest
        docker push sathwik1610/todolist-web:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml
